### ISSUE TITLE
JSON preview doesn't work

### ISSUE THREAD

**Issue by monoflash** [getinsomnia/insomnia.rest#10] opened 2017-08-03 20:33 UTC
Insomnia version Версия 5.7.0 (5.7.0.911)

![JSON preview doesn't work](https://www.dropbox.com/s/wqxypkswl6csexr/insomnia%20%D0%92%D0%B5%D1%80%D1%81%D0%B8%D1%8F%205.7.0%20%285.7.0.911%29.png?raw=1)

**Comment by gschier** [comment] 2017-08-03 20:34
This is a duplicate of https://github.com/getinsomnia/insomnia/issues/395

**Closed by gschier** 2017-08-03 20:34 UTC
